# -*- coding: utf-8 -*-
"""finetune-unsloth.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CvjECFvYNAJk_cyd_jbszMTRyDuNmInG
"""

!pip install -q transformers datasets peft trl bitsandbytes accelerate

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install unsloth
# !pip install --upgrade --no-cache-dir

"""# Load BaseModel"""

from unsloth import FastLanguageModel
import torch

max_seq_length = 2048   # Can go higher with Unsloth, no problem
dtype = None            # Auto detects Float16 for T4
load_in_4bit = True     # 4-bit quantization to save memory

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="unsloth/Phi-3-mini-4k-instruct",  # Unsloth optimized version
    max_seq_length=max_seq_length,
    dtype=dtype,
    load_in_4bit=load_in_4bit,
)

model = FastLanguageModel.get_peft_model(
    model,
    r=16,                          # LoRA rank
    target_modules=[
        "q_proj", "k_proj",
        "v_proj", "o_proj",

        "gate_proj", "up_proj", "down_proj",  # Unsloth trains more layers
    ],
    lora_alpha=16,
    lora_dropout=0,                # Unsloth uses 0 for optimized kernels
    bias="none",
    use_gradient_checkpointing="unsloth",
    random_state=42,
    use_rslora=False,
    loftq_config=None,
)

alpaca_prompt = """Below is an instruction that describes a task. Write a response that appropriately completes the request.

### Instruction:
You are CollegeGPT, a friendly BTech CS exam assistant. Answer in Hinglish (Hindi + English mix). Be clear, concise and exam-focused.

### Question:
{}

### Answer:
{}"""

from google.colab import files
import json
from datasets import Dataset

# Upload dataset
print("Please upload your dataset_clean.json file...")
uploaded = files.upload()

# Load dataset
with open("dataset_clean.json", "r", encoding="utf-8") as f:
    raw_data = json.load(f)

EOS_TOKEN = tokenizer.eos_token

def formatting_prompts_func(examples):
    instructions = examples["instruction"]
    outputs = examples["output"]
    texts = []
    for instruction, output in zip(instructions, outputs):
        text = alpaca_prompt.format(instruction, output) + EOS_TOKEN
        texts.append(text)
    return {"text": texts}

dataset = Dataset.from_list(raw_data)

# Split train/test
dataset = dataset.train_test_split(test_size=0.1, seed=42)

# Format both splits
train_dataset = dataset["train"].map(formatting_prompts_func, batched=True)
test_dataset = dataset["test"].map(formatting_prompts_func, batched=True)

from trl import SFTTrainer
from transformers import TrainingArguments
from unsloth import is_bfloat16_supported

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    dataset_text_field="text",
    max_seq_length=max_seq_length,
    dataset_num_proc=2,
    packing=False,
    args=TrainingArguments(
        per_device_train_batch_size=2,
        gradient_accumulation_steps=4,
        warmup_steps=10,
        num_train_epochs=3,
        learning_rate=2e-4,
        fp16=not is_bfloat16_supported(),
        bf16=is_bfloat16_supported(),
        logging_steps=5,
        optim="adamw_8bit",
        weight_decay=0.01,
        lr_scheduler_type="linear",
        seed=42,
        output_dir="collegegpt_outputs",
        report_to="none",
    ),
)

start_gpu_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
gpu_stats = torch.cuda.get_device_properties(0)
max_memory = round(gpu_stats.total_memory / 1024 / 1024 / 1024, 3)
print(f" Trainer ready!")
print(f"   GPU: {gpu_stats.name}")
print(f"   Total GPU memory : {max_memory} GB")
print(f"   Reserved so far  : {start_gpu_memory} GB")
print(f"   Available        : {max_memory - start_gpu_memory} GB")

trainer_stats = trainer.train()

FastLanguageModel.for_inference(model)

def ask_collegegpt(question):
    inputs = tokenizer(
        [alpaca_prompt.format(question, "")],  # Empty answer = model fills it
        return_tensors="pt"
    ).to("cuda")

    outputs = model.generate(
        **inputs,
        max_new_tokens=300,
        temperature=0.7,
        do_sample=True,
        use_cache=False,  # Changed from True to False to fix the RuntimeError
    )

    response = tokenizer.batch_decode(outputs, skip_special_tokens=True)
    answer = response[0].split("### Answer:")[-1].strip()
    return answer

test_questions = [
    "TCP aur UDP mein kya difference hai?",
    "Waterfall model explain karo with phases.",
]

for q in test_questions:
    print(f"\n Q: {q}")
    answer = ask_collegegpt(q)
    print(f" A: {answer[:400]}")
    print("-" * 40)

model.save_pretrained("collegegpt_lora")
tokenizer.save_pretrained("collegegpt_lora")
print(" LoRA adapters saved!")

model.save_pretrained_merged(
    "collegegpt_merged",
    tokenizer,
    save_method="merged_16bit"
)
print(" Merged model saved!")

import shutil
from google.colab import files

shutil.make_archive("collegegpt_lora", "zip", "./collegegpt_lora")
files.download("collegegpt_lora.zip")

